/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package ch.unibe.iam.scg.javacc;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {
	
	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int PLUS = 5;
	/** RegularExpression Id. */
	int MINUS = 6;
	/** RegularExpression Id. */
	int MULTIPLY = 7;
	/** RegularExpression Id. */
	int GREATER = 8;
	/** RegularExpression Id. */
	int AND = 9;
	/** RegularExpression Id. */
	int L_BRACKET = 10;
	/** RegularExpression Id. */
	int R_BRACKET = 11;
	/** RegularExpression Id. */
	int L_CURLY_BRACKET = 12;
	/** RegularExpression Id. */
	int R_CURLY_BRACKET = 13;
	/** RegularExpression Id. */
	int L_SQUARE_BRACKET = 14;
	/** RegularExpression Id. */
	int R_SQUARE_BRACKET = 15;
	/** RegularExpression Id. */
	int SEMICOLON = 16;
	/** RegularExpression Id. */
	int COMMA = 17;
	/** RegularExpression Id. */
	int EQUALS = 18;
	/** RegularExpression Id. */
	int DOT = 19;
	/** RegularExpression Id. */
	int NOT = 20;
	/** RegularExpression Id. */
	int CLASS = 21;
	/** RegularExpression Id. */
	int PUBLIC = 22;
	/** RegularExpression Id. */
	int STATIC = 23;
	/** RegularExpression Id. */
	int EXTENDS = 24;
	/** RegularExpression Id. */
	int MAIN = 25;
	/** RegularExpression Id. */
	int NEW = 26;
	/** RegularExpression Id. */
	int SYSOUT = 27;
	/** RegularExpression Id. */
	int LENGTH = 28;
	/** RegularExpression Id. */
	int THIS = 29;
	/** RegularExpression Id. */
	int VOID = 30;
	/** RegularExpression Id. */
	int INT = 31;
	/** RegularExpression Id. */
	int BOOL = 32;
	/** RegularExpression Id. */
	int TRUE = 33;
	/** RegularExpression Id. */
	int FALSE = 34;
	/** RegularExpression Id. */
	int STRING = 35;
	/** RegularExpression Id. */
	int IF = 36;
	/** RegularExpression Id. */
	int THEN = 37;
	/** RegularExpression Id. */
	int ELSE = 38;
	/** RegularExpression Id. */
	int WHILE = 39;
	/** RegularExpression Id. */
	int RETURN = 40;
	/** RegularExpression Id. */
	int CONSTANT = 41;
	/** RegularExpression Id. */
	int DIGIT = 42;
	/** RegularExpression Id. */
	int ID = 43;
	/** RegularExpression Id. */
	int LETTER = 44;
	/** RegularExpression Id. */
	int STRANGE_CHARS_IN_ID = 45;
	
	/** Lexical state. */
	int DEFAULT = 0;
	
	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "\"+\"",
		"\"-\"", "\"*\"", "\">\"", "\"&&\"", "\"(\"", "\")\"", "\"{\"", "\"}\"", "\"[\"",
		"\"]\"", "\";\"", "\",\"", "\"=\"", "\".\"", "\"!\"", "\"class\"", "\"public\"",
		"\"static\"", "\"extends\"", "\"main\"", "\"new\"", "\"System.out.println\"",
		"\"length\"", "\"this\"", "\"void\"", "\"int\"", "\"boolean\"", "\"true\"",
		"\"false\"", "\"String\"", "\"if\"", "\"then\"", "\"else\"", "\"while\"",
		"\"return\"", "<CONSTANT>", "<DIGIT>", "<ID>", "<LETTER>",
		"<STRANGE_CHARS_IN_ID>", };
	
}
