//
// Generated by JTB 1.3.2
//

package ch.unibe.iam.scg.minijava.ast.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "class"
 * f1 -> Identifier()
 * f2 -> ( "extends" Identifier() )?
 * f3 -> "{"
 * f4 -> ( VarDeclaration() )*
 * f5 -> ( MethodDeclaration() )*
 * f6 -> "}"
 * </PRE>
 */
public class ClassDeclaration extends Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeOptional f2;
   public NodeToken f3;
   public NodeListOptional f4;
   public NodeListOptional f5;
   public NodeToken f6;

   public ClassDeclaration(NodeToken n0, Identifier n1, NodeOptional n2, NodeToken n3, NodeListOptional n4, NodeListOptional n5, NodeToken n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public ClassDeclaration(Identifier n0, NodeOptional n1, NodeListOptional n2, NodeListOptional n3) {
      f0 = new NodeToken("class");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("{");
      f4 = n2;
      f5 = n3;
      f6 = new NodeToken("}");
   }

   public void accept(ch.unibe.iam.scg.minijava.ast.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

