//
// Generated by JTB 1.3.2
//

package ch.unibe.iam.scg.minijava.ast.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "."
 * f1 -> Identifier()
 * f2 -> "("
 * f3 -> ParamList()
 * f4 -> ")"
 * </PRE>
 */
public class MethodCall extends Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public ParamList f3;
   public NodeToken f4;

   public MethodCall(NodeToken n0, Identifier n1, NodeToken n2, ParamList n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public MethodCall(Identifier n0, ParamList n1) {
      f0 = new NodeToken(".");
      f1 = n0;
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken(")");
   }

   public void accept(ch.unibe.iam.scg.minijava.ast.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

