//
// Generated by JTB 1.3.2
//

package ch.unibe.iam.scg.minijava.ast.syntaxtree;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public abstract class NodeListInterface extends Node {
   public abstract void addNode(Node n);
   public abstract Node elementAt(int i);
   public abstract java.util.Enumeration<Node> elements();
   public abstract int size();

   public abstract void accept(ch.unibe.iam.scg.minijava.ast.visitor.Visitor v);
   public abstract <R,A> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVisitor<R,A> v, A argu);
   public abstract <R> R accept(ch.unibe.iam.scg.minijava.ast.visitor.GJNoArguVisitor<R> v);
   public abstract <A> void accept(ch.unibe.iam.scg.minijava.ast.visitor.GJVoidVisitor<A> v, A argu);
}

